version: '3'
services:
  beamcoin:
    build: .
    image: helium/beamcoin
    container_name: beamcoin
    environment:
      - PORT=8333
      - NAME=beamcoin
      - GENESIS=true
    networks:
      beamcoinnet:
        ipv4_address: 10.5.0.2
    volumes:
      - /tmp/beamcoin@127.0.0.1-genesis.block:/opt/beamcoin/beamcoin@127.0.0.1-genesis.block
  miner1:
    build: .
    image: helium/beamcoin
    container_name: miner1
    environment:
      - PORT=8333
      - NAME=miner1
      - PEERS=/ip4/10.5.0.2/tcp/8333
      - GENESIS_BLOCK=beamcoin@127.0.0.1-genesis.block
    networks:
      beamcoinnet:
        ipv4_address: 10.5.0.3
    links:
      - beamcoin
    volumes:
      - /tmp/beamcoin@127.0.0.1-genesis.block:/opt/beamcoin/beamcoin@127.0.0.1-genesis.block

networks:
  beamcoinnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
